name: Owain94 - CI (PR)

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    name: PR title
    runs-on: ubuntu-latest

    steps:
      - name: PR title lint
        if: github.event_name == 'pull_request'
        uses: seferov/pr-lint-action@v1.1.1
        with:
          title-regex: '^([\w-/]+): \w+'

  validate:
    name: Validate gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: gradle/wrapper-validation-action@v1.0.3

  build:
    name: Build
    needs: [pr-lint, validate]
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - uses: actions/checkout@v2.3.1

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/runelite
          ref: master

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/plugins
          ref: master

      - uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Assembling plugins
        run: ./gradlew :loottracker:assemble :banktags:assemble :runepouch:assemble :emojis:assemble :cluescroll:assemble --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Building plugins
        run: ./gradlew :loottracker:build :banktags:build :runepouch:build :emojis:build :cluescroll:build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Upload plugins artifacts to local maven
        run: ./gradlew :loottracker:publishToMavenLocal :banktags:publishToMavenLocal :runepouch:publishToMavenLocal :emojis:publishToMavenLocal :cluescroll:publishToMavenLocal :wiki:publishToMavenLocal :slayer:publishToMavenLocal --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Building plugins
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain


  checkstyleMain:
    name: Checkstyle main
    needs: [pr-lint, validate]
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - uses: actions/checkout@v2.3.1

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/runelite
          ref: master

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/plugins
          ref: master

      - uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Assembling plugins
        run: ./gradlew :loottracker:assemble :banktags:assemble :runepouch:assemble :emojis:assemble :cluescroll:assemble --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Building plugins
        run: ./gradlew :loottracker:build :banktags:build :runepouch:build :emojis:build :cluescroll:build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Upload plugins artifacts to local maven
        run: ./gradlew :loottracker:publishToMavenLocal :banktags:publishToMavenLocal :runepouch:publishToMavenLocal :emojis:publishToMavenLocal :cluescroll:publishToMavenLocal :wiki:publishToMavenLocal :slayer:publishToMavenLocal --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Checking plugins code conventions (Main)
        run: ./gradlew checkstyleMain --console=plain

  checkstyleTest:
    name: Checkstyle test
    needs: [pr-lint, validate]
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - uses: actions/checkout@v2.3.1

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/runelite
          ref: master

      - uses: actions/checkout@v2.3.1
        with:
          repository: open-osrs/plugins
          ref: master

      - uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable (client)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Assembling client
        run: ./gradlew assemble --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Building client
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Upload client artifacts to local maven
        run: ./gradlew :http-api:publishToMavenLocal :runelite-api:publishToMavenLocal :runelite-client:publishToMavenLocal --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/runelite

      - name: Make gradlew executable (plugins)
        run: chmod +x ./gradlew
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Assembling plugins
        run: ./gradlew :loottracker:assemble :banktags:assemble :runepouch:assemble :emojis:assemble :cluescroll:assemble --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Building plugins
        run: ./gradlew :loottracker:build :banktags:build :runepouch:build :emojis:build :cluescroll:build --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Upload plugins artifacts to local maven
        run: ./gradlew :loottracker:publishToMavenLocal :banktags:publishToMavenLocal :runepouch:publishToMavenLocal :emojis:publishToMavenLocal :cluescroll:publishToMavenLocal :wiki:publishToMavenLocal :slayer:publishToMavenLocal --stacktrace -x test -x checkstyleMain --console=plain
        working-directory: /home/runner/work/OpenOSRS-RL-hub/plugins

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assembling plugins
        run: ./gradlew assemble --console=plain

      - name: Checking plugins code conventions (Test)
        run: ./gradlew checkstyleTest --console=plain

  bump:
    name: Check version numbers
    needs: [pr-lint, validate]
    runs-on: ubuntu-latest

    steps:
      - name: Extract actor repo
        shell: bash
        run: echo "##[set-output name=repo;]$(echo $(jq --raw-output .pull_request.head.repo.full_name "$GITHUB_EVENT_PATH"))"
        id: extract_actor_repo

      - name: Extract actor repo branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo $(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH"))"
        id: extract_actor_repo_branch

      - id: changedFiles
        name: Changed files exporter
        uses: futuratrepadeira/changed-files@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - uses: actions/checkout@v2.3.1

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Bump version numbers
        id: bumpNewChanged
        if: steps.changedFiles.outputs.files_created != '' && steps.changedFiles.outputs.files_updated != ''
        run: |
          ./gradlew bumpVersion --newFiles="${{ steps.changedFiles.outputs.files_created }}" --changedFiles="${{ steps.changedFiles.outputs.files_updated }}" --console=plain

      - name: Bump version numbers
        id: bumpChanged
        if: steps.changedFiles.outputs.files_created == '' && steps.changedFiles.outputs.files_updated != ''
        run: |
          ./gradlew bumpVersion --changedFiles="${{ steps.changedFiles.outputs.files_updated }}" --console=plain

      - name: Bump version numbers
        id: bumpNew
        if: steps.changedFiles.outputs.files_created != '' && steps.changedFiles.outputs.files_updated == ''
        run: |
          ./gradlew bumpVersion --newFiles="${{ steps.changedFiles.outputs.files_created }}" --console=plain

      - name: Detect changes
        id: detectChanges
        run: |
          git update-index --skip-worktree gradlew

          if ! git diff-index --quiet HEAD --; then
              git diff-index --name-only HEAD --

              exit 1
          fi

  approve:
    name: Approve
    needs: [build, checkstyleMain, checkstyleTest, bump]
    runs-on: ubuntu-latest

    steps:
      - name: Approve pull request
        if: github.event_name == 'pull_request' && github.actor == 'OpenOSRS'
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ secrets.Owain }}